#!/bin/bash
# File: trace.sh
# Usage: ./trace.sh ./your_program --arg1 --arg2
#        or ./trace.sh sleep 10
# It captures ALL packets generated by the command you pass, and nothing else.

set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <command> [args...]"
    echo "Example: $0 ./suspect_binary --config config.ini"
    exit 1
fi

# Temporary files
PCAP="/tmp/trace_$$.pcap"
LOG="/tmp/trace_$$.log"

echo "Capturing ALL network traffic generated only by your command..."
echo "Command: $*"
echo "Press Ctrl+C when finished (the program will be killed too)"
echo

# Start tcpdump capturing everything on all interfaces
sudo tcpdump -i any -w "$PCAP" --immediate-mode -U not port 22 >/dev/null 2>&1 &
TCPDUMP_PID=$!

# Give tcpdump a moment to start
sleep 0.2

# Run the actual command in background so we can wait on it
"$@" >"$LOG" 2>&1 &
CMD_PID=$!

# Wait for the command to finish OR for Ctrl+C
trap "echo; echo 'Stopping...'" INT TERM
wait $CMD_PID
USER_EXIT=$?

# Kill tcpdump cleanly
sudo kill $TCPDUMP_PID 2>/dev/null || true
wait $TCPDUMP_PID 2>/dev/null || true

echo
echo "Capture finished. Results:"
echo "════════════════════════════════════════════════════════════════"

# 1. List of resolved domains (most useful)
if command -v tshark >/dev/null 2>&1; then
    DOMAINS=$(tshark -r "$PCAP" -Y "dns.qry.type == 1 or dns.qry.type == 28" -T fields -e dns.qry.name 2>/dev/null | sort -u)
else
    DOMAINS=$(strings "$PCAP" 2>/dev/null | grep -E '^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' | sort -u || true)
fi

if [[ -n "$DOMAINS" ]]; then
    echo "DNS queries (domains contacted):"
    echo "$DOMAINS" | sed 's/^/  • /'
else
    echo "No classic DNS queries found (might use DoH or static IPs)"
fi
echo

# 2. All remote IP addresses contacted
IPS=$(tshark -r "$PCAP" -Y "ip.dst != 192.168.0.0/16 and ip.dst != 10.0.0.0/8 and ip.dst != 172.16.0.0/12 and ip.dst != 127.0.0.0/8" -T fields -e ip.dst 2>/dev/null | sort -u || true)
if [[ -n "$IPS" ]]; then
    echo "Remote IPs contacted:"
    echo "$IPS" | sed 's/^/  → /'
fi
echo

# 3. Offer to open in Wireshark
if command -v wireshark >/dev/null 2>&1; then
    read -p "Open capture in Wireshark now? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        wireshark "$PCAP" &
    fi
fi

# Final cleanup (keep the pcap for a while)
FINAL_PCAP="$HOME/$(basename "$1")_trace_$(date +%Y%m%d_%H%M%S).pcap"
rm -f "$LOG"
echo "Full packet capture saved to: $PCAP"
echo "Done."

exit $USER_EXIT
